base_url = "https://cascasting.com"

compile_sass = true

build_search_index = false

default_language = "de"

description = "Steigern Sie mit CAS Casting Ihre Produktion: Spezialisiert auf 3D-Sanddruck und Rapid Prototyping für verbesserte und umweltfreundliche Prozesse."

[markdown]
highlight_code = false

[languages.en.translations]
description = "Revolutionize your production with CAS Casting through 3D sand printing and Rapid Prototyping for more efficient and sustainable processes."
keywords = "Foundry Design, Prototype Casting, 3D Sand Printing, Reverse Engineering, Rapid Prototyping, Molding Box, Core Box, Sustainable Production, Efficiency Improvement, CO2 Reduction, Inventory Optimization, Digital Foundry Solutions, On-Demand Manufacturing, Additive Manufacturing"

[extra]
menu_imprint = "Legal Notice"
menu_reverse_engineering = "Inventory Check"
menu_supply_chain = "Inventory Check"
menu_terms = "GTCs"
